-- ============================================================
-- Oracle SQL Script (dành cho Oracle Database 12c trở lên)
-- Chuyển đổi từ MySQL dump của database scc_ht
-- ============================================================

-- Cleanup (nếu cần chạy lại)
-- DROP TABLE ... CASCADE CONSTRAINTS;
DROP TABLE ticket_pop CASCADE CONSTRAINTS;
DROP TABLE ticket_location CASCADE CONSTRAINTS;
DROP TABLE ticket_interface CASCADE CONSTRAINTS;
DROP TABLE ticket_device CASCADE CONSTRAINTS;
DROP TABLE ticket_branch CASCADE CONSTRAINTS;
DROP TABLE ht_ticket_history CASCADE CONSTRAINTS;
DROP TABLE keywords CASCADE CONSTRAINTS;
DROP TABLE chat_history CASCADE CONSTRAINTS;
DROP TABLE fact_sc_tickets CASCADE CONSTRAINTS;
DROP TABLE fact_ht_tickets CASCADE CONSTRAINTS;
DROP TABLE fact_tickets CASCADE CONSTRAINTS;
DROP TABLE fact_ticket_process CASCADE CONSTRAINTS;
DROP TABLE fact_ticket_creation CASCADE CONSTRAINTS;
DROP TABLE fact_ticket_time CASCADE CONSTRAINTS;
DROP TABLE examples CASCADE CONSTRAINTS;
DROP TABLE sessions CASCADE CONSTRAINTS;
DROP TABLE dim_ticket_description CASCADE CONSTRAINTS;
DROP TABLE dim_ticket_close CASCADE CONSTRAINTS;
DROP TABLE dim_staffs CASCADE CONSTRAINTS;
DROP TABLE dim_regions CASCADE CONSTRAINTS;
DROP TABLE dim_reasons CASCADE CONSTRAINTS;
DROP TABLE dim_queues CASCADE CONSTRAINTS;
DROP TABLE dim_processing_units CASCADE CONSTRAINTS;
DROP TABLE dim_pops CASCADE CONSTRAINTS;
DROP TABLE dim_locations CASCADE CONSTRAINTS;
DROP TABLE dim_issue_names CASCADE CONSTRAINTS;
DROP TABLE dim_issue_groups CASCADE CONSTRAINTS;
DROP TABLE dim_interfaces CASCADE CONSTRAINTS;
DROP TABLE dim_ht_support_types CASCADE CONSTRAINTS;
DROP TABLE dim_ht_steps CASCADE CONSTRAINTS;
DROP TABLE dim_ht_service_types CASCADE CONSTRAINTS;
DROP TABLE dim_ht_queue_types CASCADE CONSTRAINTS;
DROP TABLE dim_ht_customer_types CASCADE CONSTRAINTS;
DROP TABLE dim_ht_actions CASCADE CONSTRAINTS;
DROP TABLE dim_devices CASCADE CONSTRAINTS;
DROP TABLE dim_device_types CASCADE CONSTRAINTS;
DROP TABLE dim_branches CASCADE CONSTRAINTS;

--------------------------------------------------------------
-- 1. dim_branches
--------------------------------------------------------------
CREATE TABLE dim_branches (
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_name  VARCHAR2(100 CHAR),
    code         VARCHAR2(50 CHAR)
);

COMMENT ON TABLE dim_branches IS '[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Các chi nhánh|trong hệ thống. Gồm: id, branch_name, code.';
COMMENT ON COLUMN dim_branches.id IS '[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Khóa chính.|Ví dụ giá trị: 1.';
COMMENT ON COLUMN dim_branches.branch_name IS 'UNIQUE_VALUES.[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Tên đầy đủ chi nhánh|trong hệ thống. Ví dụ giá trị: "Khánh Hòa 2". Các từ khóa có thể liên quan: thông tin chi nhánh cụ thể cần tra cứu theo nhu cầu; Chi nhánh Hà Nội 10; Hà Nội 10... Ví dụ câu hỏi: Số KHG ảnh hưởng của chi nhánh Hà Nội 11 hôm qua.';
COMMENT ON COLUMN dim_branches.code IS 'UNIQUE_VALUES.[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Mã viết tắt của chi nhánh|trong hệ thống. Ví dụ giá trị: "KHA2". Các từ khóa có thể liên quan: Chi nhánh HN10, HN10. Ví dụ câu hỏi: Số KHG ảnh hưởng của HN10, HN10.';

--------------------------------------------------------------
-- 2. dim_device_types
--------------------------------------------------------------
CREATE TABLE dim_device_types (
    id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100 CHAR)
);

COMMENT ON TABLE dim_device_types IS '[Hệ thống ticket SC sự cố] Các phần tử ( hoặc loại thiết bị -  không phải nhóm phần tử ) trong hệ thống. Mỗi sự cố được gán cho một phần tử ( hoặc loại thiết bị - không phải nhóm phần tử ) chứ không phải thiết bị cụ thể. Gồm các cột: id, name.';
COMMENT ON COLUMN dim_device_types.id IS '[Hệ thống ticket SC sự cố] Khóa chính.|Ví dụ giá trị: 1.';
COMMENT ON COLUMN dim_device_types.name IS 'UNIQUE_VALUES.[Hệ thống ticket SC sự cố] Tên của phần tử (loại thiết bị)|trong hệ thống. Ví dụ giá trị: "OPMS". Các từ khóa có thể liên quan: OLT, POP, Metro broadband BRAS... Ví dụ câu hỏi: Số SC OLT phát sinh trong ngày 1/11';

--------------------------------------------------------------
-- 3. dim_devices
--------------------------------------------------------------
CREATE TABLE dim_devices (
    id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255 CHAR)
);

COMMENT ON TABLE dim_devices IS '[Hệ thống ticket SC sự cố] Các thiết bị hoặc port cụ thể|trong hệ thống. Khác với bảng device_types (lưu loại thiết bị), bảng này mô tả chi tiết từng thiết bị cụ thể. Gồm các cột: id, name.';
COMMENT ON COLUMN dim_devices.id IS '[Hệ thống ticket SC sự cố] Khóa chính.|Ví dụ giá trị: 1.';
COMMENT ON COLUMN dim_devices.name IS 'UNIQUE_VALUES.[Hệ thống ticket SC sự cố] Tên thiết bị, port pon, tập điểm|trong hệ thống. Ví dụ giá trị: "NTGP01501OPMS". Các từ khóa có thể liên quan: thông tin thiết bị cụ thể cần tra cứu theo nhu cầu (VD: HNIP11101GC16, HNIP11101GC16.00.1, HNIP111.0901/HO).';

--------------------------------------------------------------
-- 4. dim_ht_actions
--------------------------------------------------------------
CREATE TABLE dim_ht_actions (
    id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100 CHAR)
);

COMMENT ON TABLE dim_ht_actions IS '[Hệ thống ticket HT hỗ trợ kỹ thuật] Thông tin các hành động trong Hệ thống ticket HT hỗ trợ kỹ thuật. Gồm các cột: id, name, description.';
COMMENT ON COLUMN dim_ht_actions.id IS '[Hệ thống ticket HT hỗ trợ kỹ thuật] Khóa chính.|Ví dụ giá trị: 1.';
COMMENT ON COLUMN dim_ht_actions.name IS 'UNIQUE_VALUES.[Hệ thống ticket HT hỗ trợ kỹ thuật] Tên thao tác cập nhật xử lý|ticket.Ví dụ giá trị: Xác nhận, START PROCESS.';

--------------------------------------------------------------
-- 5. dim_ht_customer_types
--------------------------------------------------------------
CREATE TABLE dim_ht_customer_types (
    id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100 CHAR)
);

COMMENT ON TABLE dim_ht_customer_types IS '[Hệ thống ticket HT hỗ trợ kỹ thuật] Thông tin các loại khách hàng, phần tử|đang có nhu cầu kiểm tra, xử lý yêu cầu. Gồm các cột: id, name.';
COMMENT ON COLUMN dim_ht_customer_types.id IS '[Hệ thống ticket HT hỗ trợ kỹ thuật] Khóa chính.|Ví dụ giá trị: 1000.';
COMMENT ON COLUMN dim_ht_customer_types.name IS 'UNIQUE_VALUES.[Hệ thống ticket HT hỗ trợ kỹ thuật] Tên loại khách hàng, phần tử|có nhu cầu kiểm tra, xử lý yêu cầu. Ví dụ giá trị: Hosting, Voice Doanh Nghiệp. Các từ khóa có thể liên quan: Loại KHG + thông tin cần tra cứu.';

--------------------------------------------------------------
-- 6. dim_ht_queue_types
--------------------------------------------------------------
CREATE TABLE dim_ht_queue_types (
    id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100 CHAR)
);

COMMENT ON TABLE dim_ht_queue_types IS '[Hệ thống ticket HT hỗ trợ kỹ thuật] Thông tin các vai trò của queue|trong Hệ thống ticket HT hỗ trợ kỹ thuật. Gồm các cột: id, name.';
COMMENT ON COLUMN dim_ht_queue_types.id IS '[Hệ thống ticket HT hỗ trợ kỹ thuật] Khóa chính.|Ví dụ giá trị: 1.';
COMMENT ON COLUMN dim_ht_queue_types.name IS 'UNIQUE_VALUES.[Hệ thống ticket HT hỗ trợ kỹ thuật] Vai trò của queue.|Ví dụ giá trị: Đơn vị TẠO, Đơn vị THỰC HIỆN.';

--------------------------------------------------------------
-- 7. dim_ht_service_types
--------------------------------------------------------------
CREATE TABLE dim_ht_service_types (
    id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100 CHAR)
);

COMMENT ON TABLE dim_ht_service_types IS '[Hệ thống ticket HT hỗ trợ kỹ thuật] Thông tin các loại dịch vụ|đang phát sinh yêu cầu hỗ trợ. Gồm các cột: id, name.';
COMMENT ON COLUMN dim_ht_service_types.id IS '[Hệ thống ticket HT hỗ trợ kỹ thuật] Khóa chính.|Ví dụ giá trị: 1000.';
COMMENT ON COLUMN dim_ht_service_types.name IS 'UNIQUE_VALUES.[Hệ thống ticket HT hỗ trợ kỹ thuật] Tên nhóm phần tử, loại dịch vụ|đang phát sinh yêu cầu hỗ trợ. Ví dụ giá trị: FTQ - Hỗ trợ quy trình, DVKH - Nghiệp vụ. Các từ khóa có thể liên quan: Có bao nhiêu ticket phát sinh thuộc loại dịch vụ + thông tin tra cứu.';

--------------------------------------------------------------
-- 8. dim_ht_steps
--------------------------------------------------------------
CREATE TABLE dim_ht_steps (
    id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100 CHAR)
);

COMMENT ON TABLE dim_ht_steps IS '[Hệ thống ticket HT hỗ trợ kỹ thuật] Thông tin các bước, tiến trình xử lý|của ticket. Gồm các cột: id, name.';
COMMENT ON COLUMN dim_ht_steps.id IS '[Hệ thống ticket HT hỗ trợ kỹ thuật] Khóa chính.|Ví dụ giá trị: 1000.';
COMMENT ON COLUMN dim_ht_steps.name IS 'UNIQUE_VALUES.[Hệ thống ticket HT hỗ trợ kỹ thuật] Tình trạng, bước, tiến trình xử lý|của ticket, thể hiện ticket đang ở tiến trình xử lý nào. Ví dụ giá trị: Đóng, Phân công/Nhận xử lý. Các từ khóa có thể liên quan: Có bao nhiêu ticket đang ở bước: Xác nhận thực hiện xong.';

--------------------------------------------------------------
-- 9. dim_ht_support_types
--------------------------------------------------------------
CREATE TABLE dim_ht_support_types (
    id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100 CHAR)
);

COMMENT ON TABLE dim_ht_support_types IS '[Hệ thống ticket HT hỗ trợ kỹ thuật] Thông tin các loại hỗ trợ.|Gồm các cột: id, name.';
COMMENT ON COLUMN dim_ht_support_types.id IS '[Hệ thống ticket HT hỗ trợ kỹ thuật] Khóa chính.|Ví dụ giá trị: 1000.';
COMMENT ON COLUMN dim_ht_support_types.name IS 'UNIQUE_VALUES.[Hệ thống ticket HT hỗ trợ kỹ thuật] Tên loại hỗ trợ|. Ví dụ giá trị: Hỗ trợ nghiệp vụ.';

--------------------------------------------------------------
-- 10. dim_interfaces
--------------------------------------------------------------
CREATE TABLE dim_interfaces (
    id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100 CHAR)
);

COMMENT ON TABLE dim_interfaces IS '[Hệ thống ticket SC sự cố] Các interface hoặc port cụ thể.|Khác với thiết bị (devices) và loại thiết bị (device_types), bảng này mô tả chính xác port/interface liên quan đến từng sự cố. Gồm các cột: id, name.';
COMMENT ON COLUMN dim_interfaces.id IS '[Hệ thống ticket SC sự cố] Khóa chính.|Ví dụ giá trị: 1.';
COMMENT ON COLUMN dim_interfaces.name IS 'UNIQUE_VALUES.[Hệ thống ticket SC sự cố] Tên port hoặc interface|trong hệ thống. Ví dụ giá trị: "XGE1/0/17". Các từ khóa có thể liên quan: Port + thông tin port cụ thể, interface + thông tin interface cụ thể như Port et-1/1/1, interface et-1/1/1.';

--------------------------------------------------------------
-- 11. dim_issue_groups
--------------------------------------------------------------
CREATE TABLE dim_issue_groups (
    id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100 CHAR)
);

COMMENT ON TABLE dim_issue_groups IS '[Hệ thống ticket SC sự cố] Các **nhóm phần tử (nhóm hệ thống)|phát sinh sự cố**. Gồm các cột: id, name.';
COMMENT ON COLUMN dim_issue_groups.id IS '[Hệ thống ticket SC sự cố] Khóa chính.|Ví dụ giá trị: 1.';
COMMENT ON COLUMN dim_issue_groups.name IS 'UNIQUE_VALUES.[Hệ thống ticket SC sự cố] Tên của nhóm thiết bị, hệ thống|gặp sự cố. Ví dụ giá trị: "Hệ thống Access". Các từ khóa có thể liên quan: Nhóm phần tử, hệ thống, Nhóm phần tử Access, hệ thống access. Ví dụ câu hỏi: Hệ thống Core IP có phát sinh sự cố với mô tả thiết bị down 1 tháng gần nhất không.';

--------------------------------------------------------------
-- 12. dim_issue_names
--------------------------------------------------------------
CREATE TABLE dim_issue_names (
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           CLOB,
    issue_group_id NUMBER(10),
    CONSTRAINT fk_issue_names_group FOREIGN KEY (issue_group_id)
        REFERENCES dim_issue_groups (id)
        ON DELETE CASCADE
);

COMMENT ON TABLE dim_issue_names IS '[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Các tên/mô tả sự cố.|Gồm các cột: id, name, issue_group_id (chỉ hệ thống SC).';
COMMENT ON COLUMN dim_issue_names.id IS '[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Khóa chính.|Ví dụ giá trị: 1';
COMMENT ON COLUMN dim_issue_names.name IS 'UNIQUE_VALUES.[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Mô tả tên của sự cố xảy ra.|Ví dụ giá trị: "Khách hàng mất kết nối". Các từ khóa có thể liên quan: Mô tả + thông tin cụ thể cần tra cứu theo nhu cầu. Ví dụ câu hỏi: có bao nhiêu SC mô tả POP down trong tuần 42 năm 2025, top 5 mô tả ticket HT queue SCC phát sinh nhiều nhất hôm nay';
COMMENT ON COLUMN dim_issue_names.issue_group_id IS '[Hệ thống ticket SC sự cố] ID của nhóm thiết bị/hệ thống|liên quan đến sự cố. Ví dụ giá trị: 1.';

CREATE INDEX idx_issue_names_group ON dim_issue_names (issue_group_id);

--------------------------------------------------------------
-- 13. dim_locations
--------------------------------------------------------------
CREATE TABLE dim_locations (
    id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255 CHAR)
);

COMMENT ON TABLE dim_locations IS '[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Các vùng địa lý.|Cần phân biệt với bảng regions (một bảng khác trong hệ thống). Gồm các cột: id, name.';
COMMENT ON COLUMN dim_locations.id IS '[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Khóa chính.|Ví dụ giá trị: 1.';
COMMENT ON COLUMN dim_locations.name IS 'UNIQUE_VALUES.[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Tên đầy đủ của vùng địa lý, khu vực.|Ví dụ giá trị: 01. Hà Nội. Các từ khóa có thể liên quan: thông tin vùng, khu vực cụ thể cần tra cứu theo nhu cầu (Hà Nội, Tây Bắc Bộ, 01. Hà Nội, 15. Tây Nam Bộ, khu vực Hà Nội, khu vực Tây Nam Bộ, vùng Tây Nam Bộ, vùng TNB, Khu vực TNB).';

--------------------------------------------------------------
-- 14. dim_pops
--------------------------------------------------------------
CREATE TABLE dim_pops (
    id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100 CHAR)
);

COMMENT ON TABLE dim_pops IS '[Hệ thống ticket SC sự cố] Các POP.|Gồm các cột: id, name.';
COMMENT ON COLUMN dim_pops.id IS '[Hệ thống ticket SC sự cố] Khóa chính.|Ví dụ giá trị: 1.';
COMMENT ON COLUMN dim_pops.name IS 'UNIQUE_VALUES.[Hệ thống ticket SC sự cố] Tên của POP.|Ví dụ giá trị: "POP-HN1". Các từ khóa có thể liên quan: thông tin POP cụ thể cần tra cứu theo nhu cầu (VD: HNIP111).';

--------------------------------------------------------------
-- 15. dim_processing_units
--------------------------------------------------------------
CREATE TABLE dim_processing_units (
    id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100 CHAR)
);

COMMENT ON TABLE dim_processing_units IS '[Hệ thống ticket SC sự cố] Các đơn vị chịu trách nhiệm xử lý|ticket. Một số đơn vị có thể là tập hợp của nhiều queue. Mỗi ticket khi được nhận xử lý đều gắn với một đơn vị xử lý. Gồm các cột: id, name.';
COMMENT ON COLUMN dim_processing_units.id IS '[Hệ thống ticket SC sự cố] Khóa chính.|Ví dụ giá trị: 1.';
COMMENT ON COLUMN dim_processing_units.name IS 'UNIQUE_VALUES.[Hệ thống ticket SC sự cố] Tên đầy đủ của đơn vị xử lý|ticket, gần tương đồng với queue_process, nhưng trường này gom một số queue_process lại thành một, các đơn vị khác giữ nguyên. Ví dụ giá trị: "Hạ tầng". Các từ khóa có thể liên quan: Hạ tầng, thuê bao, INF, đơn vị INF, TIN/PNC, TIN, PNC.';

--------------------------------------------------------------
-- 16. dim_queues
--------------------------------------------------------------
CREATE TABLE dim_queues (
    id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100 CHAR)
);

COMMENT ON TABLE dim_queues IS '[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Các queue tham gia khởi tạo hoặc xử lý|ticket. Mỗi ticket được đưa vào một hoặc nhiều queue từ khởi tạo đến xử lý. Một số queue có thể trùng với đơn vị xử lý (processing_units). Gồm các cột: id, name.';
COMMENT ON COLUMN dim_queues.id IS '[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Khóa chính.|Ví dụ giá trị: 1.';
COMMENT ON COLUMN dim_queues.name IS 'UNIQUE_VALUES.[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Tên đầy đủ của queue tham gia khởi tạo hoặc xử lý|ticket. Ví dụ giá trị: "CSOC-IT". Các từ khóa có thể liên quan: SCC tạo, INF-BTHT tạo, TIN tạo… (Tên queue + tạo); SCC xử lý, INF-BTHT xử lý, TIN xử lý… (Tên queue + xử lý).';

--------------------------------------------------------------
-- 17. dim_reasons
--------------------------------------------------------------
CREATE TABLE dim_reasons (
    id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name   CLOB,
    detail CLOB
);

COMMENT ON TABLE dim_reasons IS '[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Các nguyên nhân phát sinh, gây ra|sự cố. Gồm các cột: id, name, detail(chỉ hệ thống SC).';
COMMENT ON COLUMN dim_reasons.id IS '[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Khóa chính.|Ví dụ giá trị: 1.';
COMMENT ON COLUMN dim_reasons.name IS 'UNIQUE_VALUES.[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Tên ngắn gọn của nguyên nhân.|Ví dụ giá trị: "Bộ OPMS Cảnh Báo". Các từ khóa có thể liên quan: Nguyên nhân, NN, NNCT + thông tin chi tiết cần tra cứu.';
COMMENT ON COLUMN dim_reasons.detail IS 'UNIQUE_VALUES.[Hệ thống ticket SC sự cố] Mô tả chi tiết nguyên nhân phát sinh|. Ví dụ giá trị: "Cảnh báo đóng, mở cửa". Các từ khóa có thể liên quan: Nguyên nhân, NN, NNCT + thông tin chi tiết cần tra cứu';

--------------------------------------------------------------
-- 18. dim_regions
--------------------------------------------------------------
CREATE TABLE dim_regions (
    id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100 CHAR)
);

COMMENT ON TABLE dim_regions IS '[Hệ thống ticket SC sự cố] Các miền.|Cần phân biệt với bảng locations (vùng/khu vực chi tiết). Gồm các cột: id, name.';
COMMENT ON COLUMN dim_regions.id IS '[Hệ thống ticket SC sự cố] Khóa chính.|Ví dụ giá trị: 1.';
COMMENT ON COLUMN dim_regions.name IS 'UNIQUE_VALUES.[Hệ thống ticket SC sự cố] Tên vùng, khu vực, miền|, gom khu miền Bắc thành MB, khu miền Nam thành MN. Ví dụ giá trị: "MN". Các từ khóa có thể liên quan: MB, MN, Miền bắc, miền nam.';

--------------------------------------------------------------
-- 19. dim_staffs
--------------------------------------------------------------
CREATE TABLE dim_staffs (
    id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100 CHAR),
    mail VARCHAR2(100 CHAR)
);

COMMENT ON TABLE dim_staffs IS '[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Các nhân sự.|Gồm các cột: id, name, mail.';
COMMENT ON COLUMN dim_staffs.id IS '[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Khóa chính.|Ví dụ giá trị: 1.';
COMMENT ON COLUMN dim_staffs.name IS 'UNIQUE_VALUES.[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Ý nghĩa: Tên đầy đủ của nhân sự.|Ví dụ giá trị: "Nguyen Minh Quan". Ví dụ câu hỏi: Số SC do Lê Văn Mạnh tạo trong ngày 1/11.';
COMMENT ON COLUMN dim_staffs.mail IS 'UNIQUE_VALUES.[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Email của nhân sự|, phần prefix của email có thể được sử dụng làm tên gọi trong hệ thống. Ví dụ giá trị: "QuanNM96@fpt.com". Ví dụ câu hỏi: Số SC do ManhLV6 tạo trong ngày 1/11.';

--------------------------------------------------------------
-- 20. dim_ticket_close
--------------------------------------------------------------
CREATE TABLE dim_ticket_close (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    closed_shift  VARCHAR2(10 CHAR) CHECK (closed_shift IN ('Ca 1', 'Ca 2')),
    closed_day    DATE,
    closed_week   VARCHAR2(20 CHAR),
    closed_month  VARCHAR2(20 CHAR),
    closed_year   NUMBER(4)
);

COMMENT ON TABLE dim_ticket_close IS '[Hệ thống ticket HT hỗ trợ kỹ thuật] Thông tin chi tiết về việc đóng, hoàn tất xử lý|ticket. Bao gồm thông tin về ca đóng, ngày/tuần/tháng/năm đóng. Gồm các cột: id, closed_shift, closed_day, closed_week, closed_month, closed_year.';
COMMENT ON COLUMN dim_ticket_close.id IS '[Hệ thống ticket HT hỗ trợ kỹ thuật] Khóa chính.|Ví dụ giá trị: 10234.';
COMMENT ON COLUMN dim_ticket_close.closed_shift IS 'UNIQUE_VALUES.[Hệ thống ticket HT hỗ trợ kỹ thuật] Ca đóng, hoàn tất xử lý|theo thời gian trực của nhân sự. Ví dụ giá trị: "Ca 1". Các từ khóa có thể liên quan: Ca 1, ca 2, ca ngày (tương đương ca 1), ca đêm (tương đương ca 2).';
COMMENT ON COLUMN dim_ticket_close.closed_day IS '[Hệ thống ticket HT hỗ trợ kỹ thuật] Ngày đóng, hoàn tất xử lý|ticket. Ví dụ giá trị: "2025-10-25". Các từ khóa có thể liên quan: định dạng ngày có thể hỏi: 11/10, 11/10/2025, 11 tháng 10, 11-10, 11-10-2025.';
COMMENT ON COLUMN dim_ticket_close.closed_week IS 'UNIQUE_VALUES.[Hệ thống ticket HT hỗ trợ kỹ thuật] Tuần của năm khi đóng, hoàn tất xử lý|ticket. Ví dụ giá trị: "W43 - 2025". Các từ khóa có thể liên quan: Tuần 44, W44, Weak 44, tuần 44 năm 2025, tuần 44/2025, W44/2025, W44-2025, W44 - 2025, tuần 44 - 2025, tuần 44 - năm 2025.';
COMMENT ON COLUMN dim_ticket_close.closed_month IS 'UNIQUE_VALUES.[Hệ thống ticket HT hỗ trợ kỹ thuật] Tháng đóng, hoàn tất xử lý|ticket. Ví dụ giá trị: "10/2025". Các từ khóa có thể liên quan: Tháng 10, tháng 10 năm 2025, tháng 10/2025, 10/2025.';
COMMENT ON COLUMN dim_ticket_close.closed_year IS '[Hệ thống ticket HT hỗ trợ kỹ thuật] Năm đóng, hoàn tất xử lý|ticket. Ví dụ: 2025.';

--------------------------------------------------------------
-- 21. dim_ticket_description
--------------------------------------------------------------
CREATE TABLE dim_ticket_description (
    id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_description CLOB,
    description       CLOB
);

COMMENT ON TABLE dim_ticket_description IS '[Hệ thống ticket SC sự cố] Các mô tả và ghi chú|của ticket. Gồm các cột: id, first_description, description.';
COMMENT ON COLUMN dim_ticket_description.id IS '[Hệ thống ticket SC sự cố] Khóa chính.|Ví dụ giá trị: 1.';
COMMENT ON COLUMN dim_ticket_description.first_description IS '[Hệ thống ticket SC sự cố] Ghi chú đầu tiên|ngay từ khi ticket được khởi tạo. Ví dụ giá trị: "TNNP065.044.048/HO TD mất tín hiệu". Ví dụ câu hỏi: Các SC có B2B trong description.';
COMMENT ON COLUMN dim_ticket_description.description IS '[Hệ thống ticket SC sự cố] Ghi chú mô tả chi tiết do các đơn vị cập nhật trong, sau quá trình quản lý|của ticket. Ví dụ giá trị: "Thiết bị  NTGP051.0311/HO_FTTHNew  cảnh báo  Phần tử Tập điểm NTGP051.0311/HO_FTTHNew DOWN". Ví dụ câu hỏi: SC có ghi chú ticket chứa kí tự: B2B.';

--------------------------------------------------------------
-- 22. examples
--------------------------------------------------------------
CREATE TABLE examples (
    question CLOB NOT NULL,
    answer   CLOB
);

COMMENT ON TABLE examples IS 'Bảng chứa câu hỏi và câu trả lời mẫu.';

--------------------------------------------------------------
-- 23. sessions
--------------------------------------------------------------
CREATE TABLE sessions (
    session_id  VARCHAR2(50 CHAR) PRIMARY KEY,
    user_id     VARCHAR2(100 CHAR),
    started_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_active TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ended_at    TIMESTAMP
);

COMMENT ON TABLE sessions IS 'Bảng quản lý phiên chat.';
COMMENT ON COLUMN sessions.session_id IS 'ID phiên.';
COMMENT ON COLUMN sessions.user_id IS 'ID người dùng.';
COMMENT ON COLUMN sessions.started_at IS 'Thời điểm bắt đầu.';
COMMENT ON COLUMN sessions.last_active IS 'Lần cuối hoạt động.';
COMMENT ON COLUMN sessions.ended_at IS 'Thời điểm kết thúc.';

--------------------------------------------------------------
-- 24. fact_ticket_time (độc lập)
--------------------------------------------------------------
CREATE TABLE fact_ticket_time (
    id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    closed_date      DATE,
    estimate_date    DATE,
    expect_end_date  DATE,
    inprogress_date  DATE,
    issue_date       DATE,
    resolved_date    DATE,
    required_date    DATE,
    full_data_date   DATE
);

COMMENT ON TABLE fact_ticket_time IS '[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Chi tiết các mốc thời gian quan trọng|của ticket sự cố. Bao gồm: thời điểm phát sinh, bắt đầu xử lý, dự kiến hoàn thành, thời gian resolved, closed, required và thời gian quy định xử lý. Gồm các cột: id, closed_date(Chỉ hệ thống SC), estimate_date, expect_end_date, inprogress_date, issue_date(Chỉ hệ thống SC), resolved_date, required_date, full_data_date(Chỉ hệ thống HT).';
COMMENT ON COLUMN fact_ticket_time.id IS '[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Khóa chính.|Ví dụ giá trị: 1001.';
COMMENT ON COLUMN fact_ticket_time.closed_date IS '[Hệ thống ticket SC sự cố] Thời điểm đóng chính thức, hoàn tất xử lý|ticket sự cố, tức ticket sự cố không còn mở nữa. Ví dụ giá trị: "2025-10-25 18:30:00". Các từ khóa có thể liên quan: Thời gian closed + thời gian cụ thể cần tra cứu theo nhu cầu; Thời gian đóng SC + thời gian cụ thể cần tra cứu theo nhu cầu. Ví dụ câu hỏi: Thời điểm closed SC30102500436 là khi nào?';
COMMENT ON COLUMN fact_ticket_time.estimate_date IS '[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Thời gian quy định xử lý hoàn tất|theo từng loại sự cố. Ví dụ giá trị: "2025-10-25 17:00:00". Các từ khóa có thể liên quan: Thời gian quy định hoàn thành + thời gian cụ thể cần tra cứu theo nhu cầu; Ví dụ câu hỏi: Các SC có thời gian quy định hoàn thành trước 12:00 ngày 1/11/2025';
COMMENT ON COLUMN fact_ticket_time.expect_end_date IS '[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Thời gian dự kiến xử lý hoàn tất|do đơn vị cập nhật trong quá trình xử lý ticket. Ví dụ giá trị: "2025-10-25 18:00:00". Các từ khóa có thể liên quan: Thời gian dự kiến hoàn thành/hoàn tất/khôi phục + thời gian cụ thể cần tra cứu theo nhu cầu. Ví dụ câu hỏi: Các SC có thời gian dự kiến hoàn thành quá hạn so với hiện tại';
COMMENT ON COLUMN fact_ticket_time.inprogress_date IS '[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Thời điểm ticket bắt đầu được nhận xử lý|thực tế. Ví dụ giá trị: "2025-10-25 09:30:00". Các từ khóa có thể liên quan: Thời gian inprogress / nhận xử lý thể cần tra cứu theo nhu cầu. Ví dụ câu hỏi: Thời gian inprogress của SC30102500436.';
COMMENT ON COLUMN fact_ticket_time.issue_date IS '[Hệ thống ticket SC sự cố] Thời điểm phát sinh|sự cố, xuất hiện sự cố hoặc log cảnh báo từ hệ thống giám sát. Ví dụ giá trị: "2025-10-25 09:00:00". Các từ khóa có thể liên quan: Thời gian phát sinh + thời gian cụ thể cần tra cứu theo nhu cầu. Ví dụ câu hỏi: Các SC có thời gian phát sinh sau 00h ngày 1/11';
COMMENT ON COLUMN fact_ticket_time.resolved_date IS '[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Thời điểm được giải quyết, resolved|của ticket, tức sự cố đã được khắc phục và xử lý xong. Ví dụ giá trị: "2025-10-25 17:50:00". Các từ khóa có thể liên quan: Thời gian resolved + thời gian cụ thể cần tra cứu theo nhu cầu';
COMMENT ON COLUMN fact_ticket_time.required_date IS '[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Thời điểm cam kết được hoàn tất xử lý|của ticket sự cố. Ví dụ giá trị: "2025-10-25 18:00:00". Các từ khóa có thể liên quan: Thời gian xử lý hoàn tất + thời gian cụ thể cần tra cứu theo nhu cầu';
COMMENT ON COLUMN fact_ticket_time.full_data_date IS '[Hệ thống ticket HT hỗ trợ kỹ thuật] Thời điểm được cập nhật đầy đủ thông tin theo kịch bản và xác nhận, chuyển cho đơn vị xử lý|của ticket. Ví dụ giá trị: "2025-10-25 18:00:00". Các từ khóa có thể liên quan: Thời điểm xác nhận/hoàn tất kịch bản + thời gian cụ thể cần tra cứu theo nhu cầu.';

--------------------------------------------------------------
-- 25. fact_ticket_creation
--------------------------------------------------------------
CREATE TABLE fact_ticket_creation (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sc_creation_method  VARCHAR2(50 CHAR) CHECK (sc_creation_method IN ('SC tạo auto', 'SC tạo manual (SC tạo tay)')),
    sc_creation_time    NUMBER,
    created_staff_id    NUMBER(10),
    created_datetime    DATE,
    "date"              DATE,
    "week"              VARCHAR2(50 CHAR),
    "month"             VARCHAR2(50 CHAR),
    "period"            VARCHAR2(50 CHAR),
    "year"              NUMBER(4),
    "shift"             VARCHAR2(10 CHAR) CHECK ("shift" IN ('Ca 1', 'Ca 2')),
    CONSTRAINT fk_fact_ticket_creation_staff FOREIGN KEY (created_staff_id)
        REFERENCES dim_staffs (id)
        ON DELETE CASCADE
);

COMMENT ON TABLE fact_ticket_creation IS '[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Thông tin chi tiết về việc khởi tạo|ticket. Bao gồm thông tin về phương thức tạo, thời gian tạo, thời điểm tạo, nhân sự tạo, ngày/tháng/tuần/năm/kỳ xảy ra sự cố và ca trực. Gồm các cột: id, sc_creation_method(Chỉ hệ thống SC), sc_creation_time(Chỉ hệ thống SC), created_staff_id(Chỉ hệ thống HT), created_datetime, date, week, month, period(Chỉ hệ thống SC), year, shift.';
COMMENT ON COLUMN fact_ticket_creation.id IS '[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Khóa chính.|Ví dụ giá trị: 1.';
COMMENT ON COLUMN fact_ticket_creation.sc_creation_method IS 'UNIQUE_VALUES.[Hệ thống ticket SC sự cố] Phân biệt đối tượng khởi tạo là con người/tự động.|Ví dụ giá trị: "SC tạo auto". Các từ khóa có thể liên quan: auto, manual, system tạo, máy tạo, công cụ tạo, người tạo.';
COMMENT ON COLUMN fact_ticket_creation.sc_creation_time IS '[Hệ thống ticket SC sự cố] Khoảng thời gian từ khi phát sinh đến khi được tạo|ticket (tính theo phút) . Ví dụ giá trị: 0.6. Các từ khóa có thể liên quan: thời gian tạo, thời gian phát sinh ticket, time tạo, tgian tạo, tg tạo.';
COMMENT ON COLUMN fact_ticket_creation.created_staff_id IS '[Hệ thống ticket HT hỗ trợ kỹ thuật] ID nhân viên tạo|ticket, tham chiếu people.id. Ví dụ: 45.';
COMMENT ON COLUMN fact_ticket_creation.created_datetime IS '[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Thời điểm được khởi tạo chính thức|của ticket tính theo kiểu dữ liệu datetime. Ví dụ giá trị: "2025-10-25 14:30:00". Các từ khóa có thể liên quan: Thời gian tạo + thời gian cụ thể cần tra cứu theo nhu cầu, thời gian tạo SC + thời gian cụ thể cần tra cứu theo nhu cầu, thời điểm tạo + thời gian cụ thể cần tra cứu theo nhu cầu. Ví dụ câu hỏi: Thời điểm tạo SC30102500436 là khi nào.';
COMMENT ON COLUMN fact_ticket_creation."date" IS '[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Ngày khởi tạo hoặc phát sinh(trong hệ thống HT)|ticket. Ví dụ giá trị: "2025-10-25". Các từ khóa có thể liên quan: định dạng ngày có thể hỏi: 11/10, 11/10/2025, 11 tháng 10, 11-10, 11-10-2025.';
COMMENT ON COLUMN fact_ticket_creation."week" IS '[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Tuần khởi tạo|ticket. Ví dụ giá trị: "W43 - 2025". Các từ khóa có thể liên quan: Tuần 44, W44, Week 44, tuần 44 năm 2025, tuần 44/2025, W44/2025, W44-2025, W44 - 2025, tuần 44 - 2025, tuần 44 - năm 2025.';
COMMENT ON COLUMN fact_ticket_creation."month" IS '[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Tháng khởi tạo|ticket. Ví dụ giá trị: "10/2025". Các từ khóa có thể liên quan: Tháng 10, tháng 10 năm 2025, tháng 10/2025, 10/2025.';
COMMENT ON COLUMN fact_ticket_creation."period" IS '[Hệ thống ticket SC sự cố] Kỳ khởi tạo|ticket. Ví dụ giá trị: "2H - 2025". Các từ khóa có thể liên quan: 1H, 1H-2025, 1H.2025, 1H/2025, 1H - 2025, 1H năm 2025.';
COMMENT ON COLUMN fact_ticket_creation."year" IS '[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Năm khởi tạo|ticket. Ví dụ: 2025.';
COMMENT ON COLUMN fact_ticket_creation."shift" IS 'UNIQUE_VALUES.[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Ca trực khởi tạo|theo thời gian trực của nhân sự. Ví dụ giá trị: "Ca 1". Các từ khóa có thể liên quan: Ca 1, ca 2, ca ngày (tương đương ca 1), ca đêm (tương đương ca 2).';

CREATE INDEX idx_creation_staff ON fact_ticket_creation (created_staff_id);

--------------------------------------------------------------
-- 26. fact_ticket_process
--------------------------------------------------------------
CREATE TABLE fact_ticket_process (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    process_name        VARCHAR2(255 CHAR),
    process_staff_id    NUMBER(10),
    processing_unit_id  NUMBER(10),
    queue_create_id     NUMBER(10),
    queue_process_id    NUMBER(10),
    change_queue_time   NUMBER,
    actual_time         NUMBER,
    CONSTRAINT fk_fact_ticket_process_staff FOREIGN KEY (process_staff_id)
        REFERENCES dim_staffs (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_fact_ticket_process_unit FOREIGN KEY (processing_unit_id)
        REFERENCES dim_processing_units (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_fact_ticket_process_qcreate FOREIGN KEY (queue_create_id)
        REFERENCES dim_queues (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_fact_ticket_process_qprocess FOREIGN KEY (queue_process_id)
        REFERENCES dim_queues (id)
        ON DELETE CASCADE
);

COMMENT ON TABLE fact_ticket_process IS '[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Toàn bộ quá trình xử lý ticket|bởi các đơn vị và queue khác nhau. Bao gồm thông tin thời gian thực tế xử lý, thời gian chuyển queue khởi tạo sang xử lý, các đơn vị và queue chịu trách nhiệm khởi tạo/ xử lý ticket. Mỗi ticket đều có một bộ thông tin quá trình xử lý. Gồm các cột: id, process_name(Chỉ hệ thống HT), process_staff_id(Chỉ hệ thống HT), processing_unit_id(Chỉ hệ thống SC), queue_create_id, queue_process_id, change_queue_time, actual_time.';
COMMENT ON COLUMN fact_ticket_process.id IS '[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Khóa chính.|Ví dụ giá trị: 1001.';
COMMENT ON COLUMN fact_ticket_process.process_name IS 'UNIQUE_VALUES.[Hệ thống ticket HT hỗ trợ kỹ thuật] Tên của quá trình xử lý.';
COMMENT ON COLUMN fact_ticket_process.process_staff_id IS '[Hệ thống ticket HT hỗ trợ kỹ thuật] ID của nhân viên chịu trách nhiệm xử lý|ticket, tham chiếu dim_staffs.id.';
COMMENT ON COLUMN fact_ticket_process.processing_unit_id IS '[Hệ thống ticket SC sự cố] ID của đơn vị chịu trách nhiệm xử lý|ticket, tham chiếu processing_units.id.';
COMMENT ON COLUMN fact_ticket_process.queue_create_id IS '[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] ID của queue chịu trách nhiệm khởi tạo|ticket, tham chiếu queues.id.';
COMMENT ON COLUMN fact_ticket_process.queue_process_id IS '[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] ID của queue tiếp nhận và xử lý|ticket, tham chiếu queues.id.';
COMMENT ON COLUMN fact_ticket_process.change_queue_time IS '[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Thời gian chuyển giữa các queue|của ticket (tính theo phút). Ví dụ giả trị: 15. Các từ khóa có thể liên quan: Thời gian chuyển queue + thông tin cần tra cứu.';
COMMENT ON COLUMN fact_ticket_process.actual_time IS '[Hệ thống ticket SC sự cố] Thời gian thực tế xử lý|ticket (tính theo phút), nếu bằng 0 thì tương đương với việc chưa xử lý. Khi phân tích, thống kê thông tin **liên quan tới những sự cố đã được xử lý hoặc thời gian xử lý, chỉ tính các bản ghi có actual_time > 0**, còn lại thì không phân biệt giá trị. Ví dụ giá trị: 10. Các từ khóa có thể liên quan: Thời gian xử lý, thời gian thực xử lý, tgian xử lý, tg xử lý, time xử lý. Ví dụ câu hỏi: Thời gian xử lý trung bình của các SC của chi nhánh HN11.';

CREATE INDEX idx_process_staff ON fact_ticket_process (process_staff_id);
CREATE INDEX idx_process_unit ON fact_ticket_process (processing_unit_id);
CREATE INDEX idx_process_qcreate ON fact_ticket_process (queue_create_id);
CREATE INDEX idx_process_qprocess ON fact_ticket_process (queue_process_id);

--------------------------------------------------------------
-- 27. fact_tickets (bảng trung tâm)
--------------------------------------------------------------
CREATE TABLE fact_tickets (
    id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code             VARCHAR2(50 CHAR),
    process_id       NUMBER(10),
    time_id          NUMBER(10),
    creation_id      NUMBER(10),
    closed_id        NUMBER(10),
    over_time        VARCHAR2(255 CHAR),
    reason_id        NUMBER(10),
    priority         NUMBER(2),
    ticket_status    VARCHAR2(20 CHAR) CHECK (ticket_status IN ('Closed','Inprogress','New','Rejected','Resolved','Pending','Verified')),
    issue_name_id    NUMBER(10),
    required_time    NUMBER,
    CONSTRAINT fk_fact_tickets_process FOREIGN KEY (process_id)
        REFERENCES fact_ticket_process (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_fact_tickets_time FOREIGN KEY (time_id)
        REFERENCES fact_ticket_time (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_fact_tickets_creation FOREIGN KEY (creation_id)
        REFERENCES fact_ticket_creation (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_fact_tickets_closed FOREIGN KEY (closed_id)
        REFERENCES dim_ticket_close (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_fact_tickets_reason FOREIGN KEY (reason_id)
        REFERENCES dim_reasons (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_fact_tickets_issue FOREIGN KEY (issue_name_id)
        REFERENCES dim_issue_names (id)
        ON DELETE CASCADE
);

COMMENT ON TABLE fact_tickets IS '[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Thông tin cơ bản của ticket. **Không được phép dùng lệnh FROM fact_tickets** mà cần truy vần từ các bảng fact ticket cụ thể như fact_sc_tickets, fact_ht_tickets, ... và join vào.|Chứa các khóa ngoại liên quan đến quá trình xử lý, thời gian, khởi tạo, đóng ticket, nguyên nhân, mức độ ưu tiên và tên sự cố .Gồm các cột: id, code, process_id, time_id, creation_id, closed_id(Chỉ hệ thống HT), over_time(Chỉ hệ thống SC), reason_id, priority, ticket_status, issue_name_id, required_time(Chỉ hệ thống HT).';
COMMENT ON COLUMN fact_tickets.id IS '[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Khóa chính.|Ví dụ giá trị: 4.';
COMMENT ON COLUMN fact_tickets.code IS '[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Mã định danh duy nhất (SCxxxxx hoặc HTxxxxx)|của ticket, kết hợp chữ và số. Ví dụ giá trị: "KH1510250011". Các từ khóa có thể liên quan: SCxxxxx, HTxxxxx, ticket SCxxxxx, ticket HTxxxxx, mã SCxxxxx, mã HTxxxx.';
COMMENT ON COLUMN fact_tickets.process_id IS '[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] ID của bộ thông tin quá trình xử lý|ticket, bao gồm đơn vị xử lý, queue, thời gian thực tế. Tham chiếu ticket_process.id';
COMMENT ON COLUMN fact_tickets.time_id IS '[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] ID của các mốc thời gian quan trọng|liên quan ticket. Tham chiếu ticket_time.id';
COMMENT ON COLUMN fact_tickets.creation_id IS '[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] ID của bộ thông tin khởi tạo|ticket, bao gồm người tạo, queue/đơn vị tạo, thời điểm tạo. Tham chiếu ticket_creation.id';
COMMENT ON COLUMN fact_tickets.closed_id IS '[Hệ thống ticket HT hỗ trợ kỹ thuật] ID của bộ thông tin đóng, hoàn tất xử lý|ticket, bao gồm các mốc thời gian đóng. Tham chiếu ticket_close.id';
COMMENT ON COLUMN fact_tickets.over_time IS 'UNIQUE_VALUES.[Hệ thống ticket SC sự cố] Tính đúng hạn, quá hạn|của ticket theo thời gian quy định.Nếu over_time = trễ hạn -> ticket xử lý bị quá hạn, nếu over_time = đúng hạn hoặc = RESOLVED - Đúng hạn --> ticket xử lý đúng hạn, các trường hợp khác --> Không tính. Ví dụ giá trị: Đúng hạn. Các từ khóa có thể liên quan: đúng hạn, trễ hạn, quá hạn.';
COMMENT ON COLUMN fact_tickets.reason_id IS '[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] ID của nguyên nhân.|Tham chiếu reasons.id';
COMMENT ON COLUMN fact_tickets.priority IS 'UNIQUE+VALUES.[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Mức độ nghiệm trọng|, từ 1 đến 6. Ví dụ giá trị: 4. Các từ khóa có thể liên quan: cấp 1, cấp 2, Cấp thấp nhất, mức thấp nhất (tương đương 1), Cấp cao nhất, mức cao nhất (tương đương 6).';
COMMENT ON COLUMN fact_tickets.ticket_status IS 'UNIQUE_VALUES.[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Trạng thái, tình trạng, tiến độ xử lý (chưa, đang, đã xử lý hoặc hủy)|của ticket. Mới, chưa xử lý (Tương đương NEW), Đang xử lý (Tương đương Inprogress), Đã xử lý, xử lý hoàn tất (Tương đương Resolved, Closed), Đã xử lý tạm, xử lý tạm (Tương đương Resolved), Đã hủy, đã Reject (Tương đương Rejected). Ví dụ giá trị: NEW. Các từ khóa có thể liên quan: Rejected, NEW, Inprogress, Resolved, Closed.';
COMMENT ON COLUMN fact_tickets.issue_name_id IS '[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] ID của mô tả tên|sự cố liên quan ticket. Tham chiếu issue_names.id';
COMMENT ON COLUMN fact_tickets.required_time IS '[Hệ thống ticket HT hỗ trợ kỹ thuật] Thời gian cần xử lý hoàn tất|của ticket. Ví dụ giá trị: 100. Các từ khóa có thể liên quan: Thời gian cần xử lý hoàn tất là bao lâu.';

CREATE INDEX idx_tickets_process ON fact_tickets (process_id);
CREATE INDEX idx_tickets_time ON fact_tickets (time_id);
CREATE INDEX idx_tickets_creation ON fact_tickets (creation_id);
CREATE INDEX idx_tickets_closed ON fact_tickets (closed_id);
CREATE INDEX idx_tickets_reason ON fact_tickets (reason_id);
CREATE INDEX idx_tickets_issue ON fact_tickets (issue_name_id);

--------------------------------------------------------------
-- 28. fact_ht_tickets
--------------------------------------------------------------
CREATE TABLE fact_ht_tickets (
    ticket_id              NUMBER PRIMARY KEY,
    title                  CLOB,
    commitment_desc        VARCHAR2(10 CHAR) CHECK (commitment_desc IN ('Có', 'Không')),
    required               VARCHAR2(10 CHAR) CHECK (required IN ('Có', 'Không')),
    is_ticket_open         VARCHAR2(10 CHAR) CHECK (is_ticket_open IN ('Có', 'Không')),
    sos_ticket_flag        VARCHAR2(10 CHAR) CHECK (sos_ticket_flag IN ('Có', 'Không')),
    customer_type_id       NUMBER(10),
    service_type_id        NUMBER(10),
    support_type_id        NUMBER(10),
    step_id                NUMBER(10),
    deadline_status        VARCHAR2(20 CHAR) CHECK (deadline_status IN ('Đúng hạn', 'Quá hạn')),
    rejection_count        NUMBER(10),
    response_count         NUMBER(10),
    sla_violation_count    VARCHAR2(50 CHAR),
    priority_handling_desc VARCHAR2(10 CHAR) CHECK (priority_handling_desc IN ('Có', 'Không')),
    is_escalated           VARCHAR2(10 CHAR) CHECK (is_escalated IN ('Có', 'Không')),
    scenario_confirmed     VARCHAR2(10 CHAR) CHECK (scenario_confirmed IN ('Có', 'Không')),
    ticket_age_days        NUMBER,
    CONSTRAINT fk_ht_tickets_main FOREIGN KEY (ticket_id)
        REFERENCES fact_tickets (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_ht_tickets_customer FOREIGN KEY (customer_type_id)
        REFERENCES dim_ht_customer_types (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_ht_tickets_service FOREIGN KEY (service_type_id)
        REFERENCES dim_ht_service_types (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_ht_tickets_support FOREIGN KEY (support_type_id)
        REFERENCES dim_ht_support_types (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_ht_tickets_step FOREIGN KEY (step_id)
        REFERENCES dim_ht_steps (id)
        ON DELETE CASCADE
);

COMMENT ON TABLE fact_ht_tickets IS '[Hệ thống ticket HT hỗ trợ kỹ thuật] Thông tin chi tiết về ticket của hệ thống HT hỗ trợ kỹ thuật. **Từ bảng này cần join sang bảng fact_tickets**.|Gồm các cột: ticket_id, title, commitment_desc, required, ticket_open, sos_ticket_flag, customer_type_id, service_type_id, support_type_id, step_id, deadline_status, rejection_count, response_count, sla_violation_count, priority_handling_desc, is_escalated, scenario_confirmed, ticket_age_days.';
COMMENT ON COLUMN fact_ht_tickets.ticket_id IS '[Hệ thống ticket HT hỗ trợ kỹ thuật] Khóa chính|tham chiếu tới fact_tickets.id.Ví dụ giá trị: 4.';
COMMENT ON COLUMN fact_ht_tickets.title IS '[Hệ thống ticket HT hỗ trợ kỹ thuật] Tiêu đề của ticket.';
COMMENT ON COLUMN fact_ht_tickets.commitment_desc IS 'UNIQUE+VALUES.[Hệ thống ticket HT hỗ trợ kỹ thuật] Trạng thái mô tả cam kết SLA có/không|của SCC với ticket. Ví dụ giá trị: Có, Không.';
COMMENT ON COLUMN fact_ht_tickets.required IS 'UNIQUE+VALUES.[Hệ thống ticket HT hỗ trợ kỹ thuật] Trạng thái có/không cần đơn vị SCC hỗ trợ xử lý|của ticket, chỉ của các ticket có trạng thái NEW, Inprogress, đang chưa có nhân sự xử lý hoặc đang trong quá trình xử lý, cần nhân sự xử lý, follow. Ví dụ giá trị: Có, Không.';
COMMENT ON COLUMN fact_ht_tickets.is_ticket_open IS 'UNIQUE+VALUES.[Hệ thống ticket HT hỗ trợ kỹ thuật] Trạng thái tồn tại|của ticket, chỉ của các ticket có trạng thái NEW, Inprogress, Resolved, Pending, đang chưa được xử lý hoàn tất. Ví dụ giá trị: Có, Không.';
COMMENT ON COLUMN fact_ht_tickets.sos_ticket_flag IS 'UNIQUE+VALUES.[Hệ thống ticket HT hỗ trợ kỹ thuật] Trạng thái có/không sự ưu tiên xử lý cao nhất|của ticket. Các ticket mà hợp đồng đó, khách hàng đó đã phát sinh ticket hỗ trợ trước đó và có >= 2 ticket trong vòng 7 ngày. Ticket được dán SOS vào tiêu đề để được ưu tiên. Ví dụ giá trị: Có, Không.';
COMMENT ON COLUMN fact_ht_tickets.customer_type_id IS '[Hệ thống ticket HT hỗ trợ kỹ thuật] ID của loại khách hàng phần tử đang có nhu cầu kiểm tra, xử lý yêu cầu. Tham chiếu tới customer_types.id';
COMMENT ON COLUMN fact_ht_tickets.service_type_id IS '[Hệ thống ticket HT hỗ trợ kỹ thuật] ID của loại dịch vụ đang phát sinh yêu cầu hỗ trợ. Tham chiếu tới service_types.id';
COMMENT ON COLUMN fact_ht_tickets.support_type_id IS '[Hệ thống ticket HT hỗ trợ kỹ thuật] ID của loại hỗ trợ. Tham chiếu tới support_types.id';
COMMENT ON COLUMN fact_ht_tickets.step_id IS '[Hệ thống ticket HT hỗ trợ kỹ thuật] ID của bước, tiến trình xử lý hiện tại. Tham chiếu tới dim_ht_steps.id';
COMMENT ON COLUMN fact_ht_tickets.deadline_status IS 'UNIQUE_VALUES.[Hệ thống ticket HT hỗ trợ kỹ thuật] Trạng thái đúng hạn/quá hạn việc xử lý|ticket của scc. Ví dụ giá trị: Đúng hạn, Quá hạn.';
COMMENT ON COLUMN fact_ht_tickets.rejection_count IS '[Hệ thống ticket HT hỗ trợ kỹ thuật] Số lần từ chối|nhận xử lý ticket của SCC. Ví dụ giá trị: 0.';
COMMENT ON COLUMN fact_ht_tickets.response_count IS '[Hệ thống ticket HT hỗ trợ kỹ thuật] Số lần phản hồi|(từ chối/không từ chối) nhận xử lý ticket của SCC. Ví dụ giá trị: 1.';
COMMENT ON COLUMN fact_ht_tickets.sla_violation_count IS '[Hệ thống ticket HT hỗ trợ kỹ thuật] Số lần có thời gian phản hồi quá thời gian cam kết|của SCC. Nếu không cam kết thời gian phản hồi thì giá trị là "Không". Ví dụ giá trị: 0, 1, Không.';
COMMENT ON COLUMN fact_ht_tickets.priority_handling_desc IS 'UNIQUE+VALUES.[Hệ thống ticket HT hỗ trợ kỹ thuật] Trạng thái có/không ưu tiên xử lý|của ticket. Ví dụ giá trị: Có, Không.';
COMMENT ON COLUMN fact_ht_tickets.is_escalated IS 'UNIQUE+VALUES.[Hệ thống ticket HT hỗ trợ kỹ thuật] Trạng thái có/không escalated, escalate, việc tạo cho một đơn vị khác để xử lý khi không thể trực tiếp xử lý|ticket của SCC. Ví dụ giá trị: Có, Không.';
COMMENT ON COLUMN fact_ht_tickets.scenario_confirmed IS 'UNIQUE+VALUES.[Hệ thống ticket HT hỗ trợ kỹ thuật] Trạng thái có/không việc đã update đủ thông tin và xác nhận kịch bản, chuyển cho đơn vị xử lý|của ticket.';
COMMENT ON COLUMN fact_ht_tickets.ticket_age_days IS '[Hệ thống ticket HT hỗ trợ kỹ thuật] Thời gian tồn|tính theo ngày của ticket. Ví dụ giá trị: 16.9';

CREATE INDEX idx_ht_customer ON fact_ht_tickets (customer_type_id);
CREATE INDEX idx_ht_service ON fact_ht_tickets (service_type_id);
CREATE INDEX idx_ht_support ON fact_ht_tickets (support_type_id);
CREATE INDEX idx_ht_step ON fact_ht_tickets (step_id);

--------------------------------------------------------------
-- 29. fact_sc_tickets
--------------------------------------------------------------
CREATE TABLE fact_sc_tickets (
    ticket_id                  NUMBER PRIMARY KEY,
    description_id             NUMBER(10),
    cus_qty                    NUMBER(10),
    device_type_id             NUMBER(10),
    suspend_time               NUMBER,
    sc_khg_status              VARCHAR2(10 CHAR) CHECK (sc_khg_status IN ('Có', 'Không')),
    sc_report_status           VARCHAR2(10 CHAR) CHECK (sc_report_status IN ('Có', 'Không')),
    sc_type                    VARCHAR2(20 CHAR) CHECK (sc_type IN ('Khách quan', 'Chủ quan', '')),
    region_id                  NUMBER(10),
    sc_inf_explanation_status  VARCHAR2(10 CHAR) CHECK (sc_inf_explanation_status IN ('Có', 'Không')),
    sc_natural_disaster        VARCHAR2(10 CHAR) CHECK (sc_natural_disaster IN ('Có', 'Không')),
    parent                     CLOB,
    CONSTRAINT fk_sc_tickets_main FOREIGN KEY (ticket_id)
        REFERENCES fact_tickets (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_sc_tickets_desc FOREIGN KEY (description_id)
        REFERENCES dim_ticket_description (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_sc_tickets_device FOREIGN KEY (device_type_id)
        REFERENCES dim_device_types (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_sc_tickets_region FOREIGN KEY (region_id)
        REFERENCES dim_regions (id)
        ON DELETE CASCADE
);

COMMENT ON TABLE fact_sc_tickets IS '[Hệ thống ticket SC sự cố] Thông tin chi tiết về ticket của hệ thống SC sự cố. **Từ bảng này cần join sang bảng fact_tickets**. Gồm các cột: ticket_id, description_id, cus_qty, device_type_id, suspend_time, sc_khg_status, sc_report_status, sc_type, region_id, sc_inf_explanation_status, sc_natural_disaster, parent.';
COMMENT ON COLUMN fact_sc_tickets.ticket_id IS '[Hệ thống ticket SC sự cố] Khóa chính|tham chiếu tới fact_tickets.id.Ví dụ giá trị: 1.';
COMMENT ON COLUMN fact_sc_tickets.description_id IS '[Hệ thống ticket SC sự cố] ID của bộ mô tả chi tiết|của ticket. Tham chiếu ticket_description.id';
COMMENT ON COLUMN fact_sc_tickets.cus_qty IS '[Hệ thống ticket SC sự cố] Tổng số lượng khách hàng bị ảnh hưởng|bởi sự cố. Khi thống kê tổng số khách hàng cần thêm điều kiện sc_khg_status = "Có". Ví dụ giá trị: 50. Các từ khóa có thể liên quan: KHAH, KHG ảnh hưởng, khách hàng ảnh hưởng. Ví dụ câu hỏi: Số lượng SC có KHAH > 500.';
COMMENT ON COLUMN fact_sc_tickets.device_type_id IS '[Hệ thống ticket SC sự cố] ID của phần tử (thiết bị -  không phải nhóm phần tử )|gây ra sự cố. Tham chiếu device_types.id.';
COMMENT ON COLUMN fact_sc_tickets.suspend_time IS '[Hệ thống ticket SC sự cố] Tổng thời gian bị gián đoạn của khách hàng|tính từ thời gian phát sinh sự cố đến khi sự cố được xử lý hoàn tất (Resolved hoặc Closed Sự cố). Ví dụ giá trị: 120. Các từ khóa có thể liên quan: thời gian gián đoạn, time gián đoạn, tgian gián đoạn, tg gián đoạn, tg ảnh hưởng, thời gian ảnh hưởng, time ảnh hưởng, tgian ảnh hưởng.';
COMMENT ON COLUMN fact_sc_tickets.sc_khg_status IS 'UNIQUE+VALUES.[Hệ thống ticket SC sự cố] Trạng thái ảnh hưởng khách hàng có/không|của sự cố.Ví dụ giá trị: "Có". Các từ khóa có thể liên quan: SC ảnh hưởng KHG, AHKH, KHAH, có KHAH, không KHAH, có AHKH, không AHKH, ảnh hưởng khách hàng, khách hàng ảnh hưởng, ảnh hưởng KHG, KHG ảnh hưởng.';
COMMENT ON COLUMN fact_sc_tickets.sc_report_status IS 'UNIQUE+VALUES.[Hệ thống ticket SC sự cố] Trạng thái rule báo cáo có/không|của sự cố. Ví dụ giá trị: "Có". Các từ khóa có thể liên quan: SC báo cáo, SC không báo cáo, báo cáo, rule báo cáo.';
COMMENT ON COLUMN fact_sc_tickets.sc_type IS 'UNIQUE_VALUES.[Hệ thống ticket SC sự cố] Phân loại chủ quan/khách quan|của sự cố. Ví dụ giá trị: "Khách quan". Các từ khóa có thể liên quan: Khách quan, chủ quan, SC khách quan, SC chủ quan.';
COMMENT ON COLUMN fact_sc_tickets.region_id IS '[Hệ thống ticket SC sự cố] ID miền hoặc vùng địa lý liên quan|ticket. Tham chiếu regions.id';
COMMENT ON COLUMN fact_sc_tickets.sc_inf_explanation_status IS 'UNIQUE+VALUES.[Hệ thống ticket SC sự cố] Trạng thái cần INF cung cấp thông tin, giải thích có/không|của sự cố. Ví dụ giá trị: "Có". Các từ khóa có thể liên quan: SC cần giải trình, SC lớn INF.';
COMMENT ON COLUMN fact_sc_tickets.sc_natural_disaster IS 'UNIQUE+VALUES.[Hệ thống ticket SC sự cố] Trạng thái ảnh hưởng bởi thời tiết, thiên tai có/không|của sự cố. Ví dụ giá trị: "Có". Các từ khóa có thể liên quan: thiên tai, bão lũ, lũ lụt.';
COMMENT ON COLUMN fact_sc_tickets.parent IS '[Hệ thống ticket SC sự cố] Ticket cha hoặc con.';

CREATE INDEX idx_sc_desc ON fact_sc_tickets (description_id);
CREATE INDEX idx_sc_device ON fact_sc_tickets (device_type_id);
CREATE INDEX idx_sc_region ON fact_sc_tickets (region_id);

--------------------------------------------------------------
-- 30. ht_ticket_history
--------------------------------------------------------------
CREATE TABLE ht_ticket_history (
    id                     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description            CLOB,
    updated_date           DATE,
    ht_ticket_status       VARCHAR2(20 CHAR) CHECK (ht_ticket_status IN ('New','Inprogress','Resolved','Closed','Rejected','CREATE','Pending')),
    ht_ticket_id           NUMBER,
    action_id              NUMBER(10),
    staff_id               NUMBER(10),
    step_id                NUMBER(10),
    queue_type_id          NUMBER(10),
    created_date           DATE,
    updated_queue_id       NUMBER(10),
    response_time_minutes  NUMBER,
    commitment_description VARCHAR2(10 CHAR) CHECK (commitment_description IN ('Có', 'Không')),
    CONSTRAINT fk_ht_history_ticket FOREIGN KEY (ht_ticket_id)
        REFERENCES fact_ht_tickets (ticket_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_ht_history_action FOREIGN KEY (action_id)
        REFERENCES dim_ht_actions (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_ht_history_staff FOREIGN KEY (staff_id)
        REFERENCES dim_staffs (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_ht_history_step FOREIGN KEY (step_id)
        REFERENCES dim_ht_steps (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_ht_history_qtype FOREIGN KEY (queue_type_id)
        REFERENCES dim_ht_queue_types (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_ht_history_q FOREIGN KEY (updated_queue_id)
        REFERENCES dim_queues (id)
        ON DELETE CASCADE
);

COMMENT ON TABLE ht_ticket_history IS '[Hệ thống lịch sử update HT hỗ trợ kỹ thuật] Lịch sử thay đổi của ticket HT. Gồm các cột: id, description, updated_date, ht_ticket_status, ht_ticket_id, action_id, staff_id, step_id, queue_type_id, created_date, updated_queue_id, response_time_minutes, commitment_description.';
COMMENT ON COLUMN ht_ticket_history.id IS '[Hệ thống lịch sử update HT hỗ trợ kỹ thuật] Khóa chính.|Ví dụ giá trị: 1.';
COMMENT ON COLUMN ht_ticket_history.description IS '[Hệ thống lịch sử update HT hỗ trợ kỹ thuật] Nội dung chi tiết xử lý.';
COMMENT ON COLUMN ht_ticket_history.updated_date IS '[Hệ thống lịch sử update HT hỗ trợ kỹ thuật] Thời gian cập nhật thông tin.';
COMMENT ON COLUMN ht_ticket_history.ht_ticket_status IS 'UNIQUE_VALUES.[Hệ thống lịch sử update HT hỗ trợ kỹ thuật] Trạng thái|của ticket.';
COMMENT ON COLUMN ht_ticket_history.ht_ticket_id IS '[Hệ thống lịch sử update HT hỗ trợ kỹ thuật] ID của ticket được lưu lịch sử.';
COMMENT ON COLUMN ht_ticket_history.action_id IS '[Hệ thống lịch sử update HT hỗ trợ kỹ thuật] ID của thao tác cập nhật xử lý.';
COMMENT ON COLUMN ht_ticket_history.staff_id IS '[Hệ thống lịch sử update HT hỗ trợ kỹ thuật] ID của nhân viên cập nhật xử lý.';
COMMENT ON COLUMN ht_ticket_history.step_id IS '[Hệ thống lịch sử update HT hỗ trợ kỹ thuật] ID của tình trạng, tiến trính xử lý hiện tại.';
COMMENT ON COLUMN ht_ticket_history.queue_type_id IS '[Hệ thống lịch sử update HT hỗ trợ kỹ thuật] ID của vai trò queue.';
COMMENT ON COLUMN ht_ticket_history.created_date IS '[Hệ thống lịch sử update HT hỗ trợ kỹ thuật] Thời gian tạo bản ghi lịch sử|ticket.';
COMMENT ON COLUMN ht_ticket_history.updated_queue_id IS '[Hệ thống lịch sử update HT hỗ trợ kỹ thuật] ID của queue thực hiện cập nhật xử lý.';
COMMENT ON COLUMN ht_ticket_history.response_time_minutes IS '[Hệ thống lịch sử update HT hỗ trợ kỹ thuật] Thời gian phản hồi(phút)|tính từ thời điểm được cung cấp đủ thông tin và chuyển sang SCC dến khi SCC phản hồi. Ví dụ giá trị: 1.6';
COMMENT ON COLUMN ht_ticket_history.commitment_description IS 'UNIQUE+VALUES.[Hệ thống lịch sử update HT hỗ trợ kỹ thuật] Trạng thái có/không cam kết phản hồi| từ SCC trong 1 khoảng thời gian nhất định.';

CREATE INDEX idx_ht_hist_ticket ON ht_ticket_history (ht_ticket_id);
CREATE INDEX idx_ht_hist_action ON ht_ticket_history (action_id);
CREATE INDEX idx_ht_hist_staff ON ht_ticket_history (staff_id);
CREATE INDEX idx_ht_hist_step ON ht_ticket_history (step_id);
CREATE INDEX idx_ht_hist_qtype ON ht_ticket_history (queue_type_id);
CREATE INDEX idx_ht_hist_q ON ht_ticket_history (updated_queue_id);

--------------------------------------------------------------
-- 31. chat_history (sau sessions)
--------------------------------------------------------------
CREATE TABLE chat_history (
    question_id      VARCHAR2(50 CHAR) NOT NULL,
    user_id          VARCHAR2(50 CHAR) NOT NULL,
    user_email       VARCHAR2(50 CHAR) NOT NULL,
    session_id       VARCHAR2(50 CHAR) NOT NULL,
    room_id          VARCHAR2(50 CHAR) NOT NULL,
    question         CLOB,
    answer           CLOB,
    sql_query        CLOB,
    schema_data      CLOB,   -- JSON
    asking_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (question_id, session_id, user_id),
    CONSTRAINT fk_chat_session FOREIGN KEY (session_id)
        REFERENCES sessions (session_id)
        ON DELETE CASCADE
);

COMMENT ON TABLE chat_history IS 'Bảng lưu lịch sử chat.';
COMMENT ON COLUMN chat_history.schema_data IS 'Dữ liệu schema dạng JSON (lưu trong CLOB).';

CREATE INDEX fk_chat_session_idx ON chat_history (session_id);

--------------------------------------------------------------
-- 32. keywords
--------------------------------------------------------------
CREATE TABLE keywords (
    keyword      VARCHAR2(50 CHAR) PRIMARY KEY,
    detail_value CLOB
);

COMMENT ON TABLE keywords IS 'Hệ thống quản lý ticket tích hợp, quản lý đồng thời cả ticket sự cố (SC) và ticket hỗ trợ kỹ thuật (HT). Hệ thống SC hỗ trợ truy vấn sự cố kỹ thuật phát sinh trên hạ tầng, bao gồm thời gian, thiết bị, POP, nguyên nhân, ảnh hưởng khách hàng và hiệu quả xử lý. Hệ thống HT hỗ trợ truy vấn ticket hỗ trợ kỹ thuật theo tiến trình xử lý, SLA, queue/đơn vị xử lý, nhân sự và lịch sử cập nhật.';

--------------------------------------------------------------
-- 33. ticket_branch (bridge)
--------------------------------------------------------------
CREATE TABLE ticket_branch (
    ticket_id NUMBER(10) NOT NULL,
    branch_id NUMBER(10) NOT NULL,
    PRIMARY KEY (ticket_id, branch_id),
    CONSTRAINT fk_ticket_branch_ticket FOREIGN KEY (ticket_id)
        REFERENCES fact_tickets (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_ticket_branch_branch FOREIGN KEY (branch_id)
        REFERENCES dim_branches (id)
        ON DELETE CASCADE
);

CREATE INDEX idx_tb_branch ON ticket_branch (branch_id);

COMMENT ON TABLE ticket_branch IS '[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Bảng liên kết nhiều-nhiều giữa ticket và chi nhánh phát sinh sự cố. Lưu thông tin chi nhánh nào chịu trách nhiệm hoặc nơi phát sinh sự cố của mỗi ticket.|Các cột: ticket_id, branch_id.';

--------------------------------------------------------------
-- 34. ticket_device
--------------------------------------------------------------
CREATE TABLE ticket_device (
    ticket_id NUMBER(10) NOT NULL,
    device_id NUMBER(10) NOT NULL,
    PRIMARY KEY (ticket_id, device_id),
    CONSTRAINT fk_ticket_device_ticket FOREIGN KEY (ticket_id)
        REFERENCES fact_tickets (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_ticket_device_device FOREIGN KEY (device_id)
        REFERENCES dim_devices (id)
        ON DELETE CASCADE
);

CREATE INDEX idx_td_device ON ticket_device (device_id);

COMMENT ON TABLE ticket_device IS '[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Bảng liên kết nhiều-nhiều giữa ticket và thiết bị gây ra sự cố. Mỗi ticket có thể liên quan đến nhiều thiết bị, mỗi thiết bị có thể liên quan đến nhiều ticket.|Các cột: ticket_id, device_id.';

--------------------------------------------------------------
-- 35. ticket_interface
--------------------------------------------------------------
CREATE TABLE ticket_interface (
    ticket_id    NUMBER(10) NOT NULL,
    interface_id NUMBER(10) NOT NULL,
    PRIMARY KEY (ticket_id, interface_id),
    CONSTRAINT fk_ticket_interface_ticket FOREIGN KEY (ticket_id)
        REFERENCES fact_tickets (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_ticket_interface_interface FOREIGN KEY (interface_id)
        REFERENCES dim_interfaces (id)
        ON DELETE CASCADE
);

CREATE INDEX idx_ti_interface ON ticket_interface (interface_id);

COMMENT ON TABLE ticket_interface IS '[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Bảng liên kết nhiều-nhiều giữa ticket và interface gây ra sự cố. Mỗi ticket có thể liên quan đến nhiều interface, mỗi interface có thể liên quan đến nhiều ticket.|Các cột: ticket_id, interface_id.';

--------------------------------------------------------------
-- 36. ticket_location
--------------------------------------------------------------
CREATE TABLE ticket_location (
    ticket_id   NUMBER(10) NOT NULL,
    location_id NUMBER(10) NOT NULL,
    PRIMARY KEY (ticket_id, location_id),
    CONSTRAINT fk_ticket_location_ticket FOREIGN KEY (ticket_id)
        REFERENCES fact_tickets (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_ticket_location_location FOREIGN KEY (location_id)
        REFERENCES dim_locations (id)
        ON DELETE CASCADE
);

CREATE INDEX idx_tl_location ON ticket_location (location_id);

COMMENT ON TABLE ticket_location IS '[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Bảng liên kết nhiều-nhiều giữa ticket và các vùng/khu vực gây ra sự cố. Mỗi ticket có thể liên quan đến nhiều vùng, mỗi vùng có thể liên quan đến nhiều ticket.|Các cột: ticket_id, location_id.';

--------------------------------------------------------------
-- 37. ticket_pop
--------------------------------------------------------------
CREATE TABLE ticket_pop (
    ticket_id NUMBER(10) NOT NULL,
    pop_id    NUMBER(10) NOT NULL,
    PRIMARY KEY (ticket_id, pop_id),
    CONSTRAINT fk_ticket_pop_ticket FOREIGN KEY (ticket_id)
        REFERENCES fact_tickets (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_ticket_pop_pop FOREIGN KEY (pop_id)
        REFERENCES dim_pops (id)
        ON DELETE CASCADE
);

CREATE INDEX idx_tp_pop ON ticket_pop (pop_id);

COMMENT ON TABLE ticket_pop IS '[Dùng chung Hệ thống ticket HT hỗ trợ kỹ thuật và SC sự cố] Bảng liên kết nhiều-nhiều giữa ticket và các POP gây ra sự cố. Mỗi ticket có thể liên quan đến nhiều POP, mỗi POP có thể liên quan đến nhiều ticket.|Các cột: ticket_id, pop_id.';

-- ============================================================
-- LƯU Ý:
-- 1. Các khóa ngoại từ MySQL có ON UPDATE CASCADE đã bị loại bỏ
--    vì Oracle không hỗ trợ. Nếu nghiệp vụ yêu cầu cập nhật
--    khóa chính, bạn cần viết trigger riêng.
-- 2. Cột kiểu JSON trong MySQL chuyển thành CLOB; bạn có thể
--    thêm ràng buộc CHECK (cột IS JSON) nếu dùng Oracle 12.2+.
-- 3. Chỉ mục trên khóa ngoại được tạo thủ công để tăng hiệu năng.
-- 4. Script này tương thích Oracle 12c trở lên.
-- ============================================================